NAMES_SUBSTITUTIONS = {
    "шато": "castle",
    "кара": "cara",
    "амбра": "ambra",
    "бельгия": "belga",
    "терра": "terra",
    "руби": "ruby",
    "клэр": "clair",
    "голд": "gold",
    "блонд": "blond",

    "мюник": "munich",
    "мюнхнер": "munich",
    "лайт": "light",
    "дистиллинг": "distilling",
    "диастатик": "diastatic",
    "блэк": "black",
    "бисквит": "biscuit",
    "арома": "aroma",
    "вена": "vienna",
    "пэйл": "pale",
    "пильсен": "pilsen",
    "оут": "oat",
    "мелано": "melano",
    "шоколад": "chocolat",
    "чит": "chit",
    "спешл": "special",
    "би": "b",
    "спельта": "spelt",
    "эйсид": "acid",

    "chocolad": "chocolat",
    "viena": "vienna",
    "arome": "aroma",
    "lite": "light",

    "карамельный": "cara",
    "аббатский": "abbey",
    "мюнхенский": "munich",
    "пшеничный": "wheat",
    "кофе": "cafe",
    "кристал": "crystal",
    "копченый": "smoked",
    "торфяной": "peated",
    "дробленый": "",
    "светлый": "blanc",
    "виски": "whiskey",
    "тип": "type",
    "ячмень": "barley",
    "шоколадный": "chocolate",


    "флауэр": "flower",
    "циндао": "tsingtao",
    "селект": "select",
    "шпальтер": "spalter",
    "чинук": "chinook",
    "цитра": "citra",
    "центенниал": "centennial",
    "хьюэлл": "huell",
    "мелон": "melon",
    "херсбрукер": "hersbrucker",
    "миттельфрю": "mittelfruh",
    "халлертаур": "hallertauer",
    "теттнангер": "tettnanger",
    "голдингс": "goldings",
    "ариана": "ariana",
    "эль": "el",
    "дорадо": "dorado",
    "экуанот": "ekuanot",
    "эквинокс": "equinox",
    "премиант": "premiant",
    "каскад": "cascade",
    "сапфир": "saphire",
    "традиционный": "tradition",
    "наггет": "nugget",
    "бавария": "bavaria",
    "мандарина": "mandarina",
    "магнум": "magnum",
    "перле": "perle",
    "варриор": "warrior",
    "уилламет": "willamette",
    "ист": "east",
    "кент": "kent",
    "жатецкий": "saaz",
    "гэлэкси": "galaxy",
    "геркулес": "herkules",
    "вик": "vic",
    "сикрет": "secret",
    "коламбус": "columbus",
    "кашемир": "cashmere",
    "бревер": "brewer",
    "нортен": "northen",
    "нельсон": "nelson",
    "совиньон": "sauvin",
    "мозаика": "mosaic",
    "сабро": "sabro",
    "поларис": "polaris",
    "талус": "talus",
    "сладек": "sladek",
    "симкое": "simcoe",
    "бланк": "blanc",
    "фаггл": "fuggle",
    "бобек": "bobek",
    "амарилло": "amarillo",
    "айдахо": "idaho",
    "азакка": "azacca",
    "аврора": "aurora"
}


BRANDS_SUBS = {
    "joh.barth&sohn": "barthhaas",
    "barth haas group": "barthhaas",
    "john i. haas": "barthhaas",
    "john i.haas, inc., usa": "barthhaas",
    "грейнрус хмель": "грейнрус",
    "grainrus": "грейнрус",
    "курский солод": "грейнрус",
    "органик фуд": "грейнрус"
}